set -g mode-keys vi
set -g default-terminal "st"
set -ga terminal-overrides "*:RGB"


unbind C-b 
set -g prefix C-a 
bind-key C-a send-prefix

unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


unbind r 
bind r source-file $HOME/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status "on"
set -g status-bg "#000000"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

thm_bg="#ff5656"
thm_fg="#000000"
thm_cyan="#8ff8f5"
thm_black="#000000"
thm_gray="#555555"
thm_magenta="#f650d8"
thm_pink="#ff4646"
thm_red="#ff4646"
thm_green="#73ef63"
thm_yellow="#f0f656"
thm_blue="#0096FF"
thm_orange="#ff9e64"
thm_black4="#ff2222"


set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_red}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "" 


# Statusline - other windows
set -g window-status-format ""

# Statusline - right side
set -g status-right "#[fg=${thm_red},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_black},bg=${thm_red},nobold,nounderscore,noitalics]o-o#[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_red}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_red}]}#[fg=${thm_black}]>_ #[fg=${thm_fg},bg=${thm_gray}] #S "

# Statusline - left side (empty)
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_red}"
set -g mode-style "fg=${thm_red} bg=${thm_black4} bold"
